set-option -g status-left-length 50
set-option -g status-right-length 100
set-window-option -g automatic-rename off
set -g base-index 1
set -g mouse on

# Keybindings: wasd
bind k select-pane -U
bind h select-pane -L
bind j select-pane -D
bind l select-pane -R
bind -r K resize-pane -U
bind -r H resize-pane -L
bind -r J resize-pane -D
bind -r L resize-pane -R

set -g status on
set -g status-bg colour237
set -g status-fg colour250

# Show only session name on right
set -g status-right "#[fg=colour34,bold]#S "

# Remove left-side info (optional)
set -g status-left ""

# Reload
unbind r
bind r source-file ~/.tmux.conf

# Window list formatting
setw -g window-status-format " #[fg=colour244]#I:#W "
setw -g window-status-current-format " #[fg=colour214,bold]#I:#W "

# Disable auto-renaming of windows
set -g automatic-rename off
set -g set-titles off

bind '"' split-window -v -c "#{pane_current_path}"
bind % split-window -h -c "#{pane_current_path}"


### Plugins ###

# List of plugins
set -g @plugin 'tmux-plugins/tpm'
set -g @plugin 'tmux-plugins/tmux-resurrect'
set -g @plugin 'tmux-plugins/tmux-continuum'

# PLugin settings
set -g @resurrect-delete-backup-after '0'

# Initialize TMUX plugin manager (keep this line at the very bottom of tmux.conf)
run '~/.tmux/plugins/tpm/tpm'
